source 'https://rubygems.org'
gem 'jekyll'
gem 'jekyll-archives'
gem 'jekyll-sitemap'
gem 'jekyll-paginate'
gem 'jekyll-coffeescript'
gem 'jekyll-sass-converter'
gem 'jekyll-github-metadata'
gem 'jekyll-seo-tag'
gem 'jekyll-commonmark-ghpages'
gem 'jekyll-gist'
gem 'jekyll-relative-links'
gem 'jekyll-optional-front-matter'
gem 'jekyll-readme-index'
gem 'jekyll-default-layout'
gem 'jekyll-titles-from-headings'

